"""
Django settings for emasons project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hge0cr9f)^b!32t7c10rxx2ymyh*sze++0@hb-9y3u!(x@4nko"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ==============================================================================================
# Application definition
# ==============================================================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "auditlog",
    "author",
    "django_extensions",
    "smartmin",
    # Local apps
    "apps.users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "author.middlewares.AuthorDefaultBackendMiddleware",
]

ROOT_URLCONF = "emasons.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emasons.wsgi.application"

# ==============================================================================================
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# ==============================================================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ==============================================================================================
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
# ==============================================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ==============================================================================================
# Auth
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth
# ==============================================================================================
AUTH_USER_MODEL = "users.User"

LOGIN_URL = "users:login"

# ==============================================================================================
# Smartmin
# https://smartmin.readthedocs.io/en/latest/#configuration
# ==============================================================================================
PERMISSIONS = {
    "*": (
        "create",
        "read",
        "update",
        "delete",
        "list",
    ),
}

GROUP_PERMISSIONS = {
    "admin": ("users.user.*",),
    "staff_admin": ("users.user.*",),
    "staff": (
        "users.user_read",
        "users.user_list",
    ),
}

# ==============================================================================================
# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
# ==============================================================================================
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# ==============================================================================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# ==============================================================================================
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# ==============================================================================================
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
# ==============================================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================================
# Debug settings
# ==============================================================================================
if DEBUG:
    INSTALLED_APPS += [
        "django_browser_reload",
        "debug_toolbar",
    ]

    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

    INTERNAL_IPS = [
        "127.0.0.1",
    ]
